### ISSUE TITLE
upgrade redis-parser to remove DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by takion** [NodeRedis/node-redis#1383]
Hello,

In node 10:

[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:159:11)
    at new Buffer (buffer.js:174:3)
    at bufferAlloc (/app/node_modules/redis/node_modules/redis-parser/lib/parser.js:21:47)
    at Object.<anonymous> (/app/node_modules/redis/node_modules/redis-parser/lib/parser.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/app/node_modules/redis/node_modules/redis-parser/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

see also https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/

upgrade redis-parser will solve the problem

Thanks.

**Comment by bigman73** [comment]
Is node_redis a dead project?

**Comment by stockholmux** [comment]
@bigman73 Nope.

**Comment by bigman73** [comment]
OK, thanks for clarifying that.
Could you please release an updated version that has the latest redis-parser module?

**Comment by Salakar** [comment]
The latest parser is live on master and will be in the next release, thanks

**Comment by Salakar** [comment]
Hey everyone, I've taken over as lead maintainer and have all the required access now 🎉 (thanks @BridgeAR)

I've spent the last few days getting master ready for a release, and as of a few minutes ago I've just published v3.0.0 to NPM; https://github.com/NodeRedis/node-redis/releases/tag/v3.0.0 - which includes this change.
