### ISSUE TITLE
AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.

### ISSUE THREAD

**Issue by hzb** [NodeRedis/node-redis#1533]
### Reproduce steps

1. import `redis` from npm

```
npm install redis
```

2. code of `app.js`

```
const redis = require('redis');
const client = redis.createClient();

client.on('connect', function() {
    console.log('connected');
});
```

3 . run `node app.js`

### Error information

```
connected

events.js:187
      throw er; // Unhandled 'error' event
      ^
AbortError: Ready check failed: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/Users/hb/Desktop/temp/node_modules/redis/index.js:297:23)
    at RedisClient.connection_gone (/Users/hb/Desktop/temp/node_modules/redis/index.js:602:14)
    at Socket.<anonymous> (/Users/hb/Desktop/temp/node_modules/redis/index.js:230:14)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_info_cmd (/Users/hb/Desktop/temp/node_modules/redis/index.js:431:14)
    at /Users/hb/Desktop/temp/node_modules/redis/index.js:470:14
    at Object.callbackOrEmit [as callback_or_emit] (/Users/hb/Desktop/temp/node_modules/redis/lib/utils.js:89:9)
    at Command.callback (/Users/hb/Desktop/temp/node_modules/redis/lib/individualCommands.js:157:15)
    at RedisClient.flush_and_error (/Users/hb/Desktop/temp/node_modules/redis/index.js:309:29)
    at RedisClient.connection_gone (/Users/hb/Desktop/temp/node_modules/redis/index.js:602:14)
    [... lines matching original stack trace ...]
    at endReadableNT (_stream_readable.js:1183:12) {
  code: 'UNCERTAIN_STATE',
  command: 'INFO'
}
```

### Environment

- node version

    v12.13.0
 
- redis version
    latest from Docker
 
- OS System

    macOS 10.15

**Comment by hzb** [comment]
Append: 

Reinstall the redis server without using Docker, it works well.

**Comment by stockholmux** [comment]
This sounds like an issue with your redis server (see [Error Handling on the README](https://github.com/NodeRedis/node-redis#error-handling)). `UNCERTAIN_STATE` specifically has to do with a dropped connection which can happen for a variety of reasons, but it doesn't have much to do with the node_redis code. 

I'm going to close this for now, but feel free to check back if you uncover something particularly nasty that is specific outside your server.

**Comment by sudo-kaizen** [comment]
May be too late but I had this error too.
The problem was that TLS was enabled on the redis server but the URL that I was using to connect was `redis//` instead of `rediss`.
You may want to check that if you're in this situation

**Comment by PINGPING1998** [comment]
If you use laradock to install redis, go to the redis container, and then click inspect. It will show the correct port and host there.

**Comment by goktugyil** [comment]
> May be too late but I had this error too. The problem was that TLS was enabled on the redis server but the URL that I was using to connect was `redis//` instead of `rediss//`. You may want to check that if you're in this situation

I tried that, it didn't work either

**Comment by toussa** [comment]
I also have sometimes this error with OVH managed redis (note: I used `rediss://...` ).
This is annoying because it seems it doesn't try to reconnect
