### ISSUE TITLE
🐛 Redis parser throwing an error every 1 hour

### ISSUE THREAD

**Issue by AdelUnito** [NodeRedis/node-redis#1538]
### Issue

*Issue type:**

[x] bug report
[ ] feature request

I'm getting the following error every 1 hour in production and I wasn't able to reproduce it locally

```bash
{ AbortError: Fatal error encountered. Command aborted. It might have been processed.
    at RedisClient.flush_and_error (/.../node_modules/redis/index.js:297:23)
    at JavascriptRedisParser.returnFatalError (/.../node_modules/redis/index.js:148:18)
    at handleError (/.../node_modules/redis-parser/lib/parser.js:196:10)
    at parseType (/.../node_modules/redis-parser/lib/parser.js:304:14)
    at JavascriptRedisParser.execute (/.../node_modules/redis-parser/lib/parser.js:533:24)
    at Socket.<anonymous> (/.../node_modules/redis/index.js:218:27)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
  code: 'NR_FATAL',
  command: 'INFO',
  origin:
   { ParserError: Protocol error, got "\u0015" as reply type byte. Please report this.
       at handleError (/.../node_modules/redis-parser/lib/parser.js:190:15)
       at parseType (/.../node_modules/redis-parser/lib/parser.js:304:14)
     offset: 1,
     buffer: '{"type":"Buffer","data":[21,0,0,0,2,1,0]}' } }
```

My Redis is on AWS elasticach Redis cluster.

This Redis is only used by my DB ORM `TypeORM`, you can find more details about the configuration [here](https://github.com/typeorm/typeorm/issues/6716)

---

### Environment

 - **Node.js Version**: `12.18.1`
 

 - **Redis Version**: `3.x` ==> `3.0.2`
 

 - **Platform**: `Amazon Linux` on EBS

**Comment by philwhln** [comment]
@AdelUnito Did you manage to resolve this? Have you updated `node-redis` version? We're looking at a similar issue now.

**Comment by AdelUnito** [comment]
> @AdelUnito Did you manage to resolve this? Have you updated `node-redis` version? We're looking at a similar issue now.

Hi @philwhln, Unfortunately, no I didn't manage to resolve it. I've disabled caching from [typeORM](https://github.com/typeorm/typeorm) to avoid this issue.

**Comment by philwhln** [comment]
@AdelUnito Thanks! I've managed to get to the bottom of our issue. It's was related to TLS settings not property configured in one area of the code. `\u0015` was coming back in the handshake, but the code was not expecting TLS.

**Comment by AdelUnito** [comment]
> @AdelUnito Thanks! I've managed to get to the bottom of our issue. It's was related to TLS settings not property configured in one area of the code. `\u0015` was coming back in the handshake, but the code was not expecting TLS.

@philwhln Thanks for sharing. I hope it will help someone with the same issue
