### ISSUE TITLE
Redis ( node-redis ) - Unhandled 'error' event

### ISSUE THREAD

**Issue by valdorvaldor** [NodeRedis/node-redis#1559]
**CLIENT: 3.0.2
REDIS: 5.0.3**

- Running within GCLOUD RUN ( Docker / node:14.15.4-alpine3.12 )
- Latency ~10ms 
- After started,  the app starts PINGING the redis server
- (TEST A, PING  Interval 30 seconds ) Server crashes after 8 PINGS always 
- (TEST B, PING Interval 60 seconds ) Server crashes after 3 PINGS always
- not a single event es registered in the log ( end, error, uncaughtException, reconnecting  )
- I've tried ECHO instead of PING but I got same results.
- Pinging a different Redis Server with a different IP also fails.

```
var redis__create_ping = ( client ) => {
        client.ping = setInterval(( )=>{
                let timestamp = ( new Date() ).getTime();
                client.instance.ping(  (error, pong ) => {
                        if( error ){
                                console.error( '\n<PING ERROR>', client.name, client.index );
                                console.error( error );
                        }
                        else {
                                if( __.DEBUG ){
                                        console.log( '\n<PING>', client.name, client.index, (new Date()).getTime() - timestamp );
                                }
                        };
                });
        },  30000);
};

var redis__connect = ( args , success, fail ) => {
        let { index, name } = args;
        let client = { name, index };
        let host = ___.REDIS.HOST;
        let port = ___.REDIS.PORT;
        let cli = redis.createClient({ host, port, db: index, socket_keepalive: true });
        cli.on('connect',  ready => {
                if( __.DEBUG ) console.info('\n<CONNECT>', name, index  );
                client.instance = cli;
                redis__create_ping( client );
                CLIENTS[name] = client;
                success( true );
        });

        cli.on('ready', () => {
                if( __.DEBUG ) console.info( '\n<READY>', name, index );
        });

        cli.on('reconnecting', () => {
                if( __.DEBUG ) console.info( '\n<RECONNECTING>', name, index );
        });

        cli.on('end', () => {
                if( __.DEBUG ) console.info('\n<END>', name, index  );
        });

        cli.on('uncaughtException',  error  => {
                console.error('\n<UNCAUGHT-EXCEPTION>', name, index  );
                console.error( error  );
        });

        cli.on('error', error => {
                console.error('\n<ERROR>', name, index  );
                console.error( error );
        });
};

```

**LOG**
```
...
2021-01-27 15:59:42.472 EST<PING> REDIS_CLIENT_BLOCKED_NUMBERS_WRITE 11 4
Default
2021-01-27 15:59:42.480 ESTevents.js:292
Default
2021-01-27 15:59:42.480 EST throw er; // Unhandled 'error' event
Default
2021-01-27 15:59:42.480 EST ^
Default
2021-01-27 15:59:42.480 EST
Default
2021-01-27 15:59:42.480 ESTError: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Default
2021-01-27 15:59:42.480 ESTEmitted 'error' event on RedisClient instance at:
Default
2021-01-27 15:59:42.480 EST at RedisClient.on_error (/opt/app/node_modules/redis/index.js:341:14)
Default
2021-01-27 15:59:42.480 EST at Socket.<anonymous> (/opt/app/node_modules/redis/index.js:222:14)
Default
2021-01-27 15:59:42.480 EST at Socket.emit (events.js:315:20)
Default
2021-01-27 15:59:42.480 EST at emitErrorNT (internal/streams/destroy.js:106:8)
Default
2021-01-27 15:59:42.480 EST at emitErrorCloseNT (internal/streams/destroy.js:74:3)
Default
2021-01-27 15:59:42.480 EST at processTicksAndRejections (internal/process/task_queues.js:80:21) {
Default
2021-01-27 15:59:42.480 EST errno: -104,
Default
2021-01-27 15:59:42.480 EST code: 'ECONNRESET',
Default
2021-01-27 15:59:42.480 EST syscall: 'read'
Default
2021-01-27 15:59:42.480 EST}
Warning
2021-01-27 15:59:46.579 ESTContainer called exit(1).
```

**TEST WITH SIMPLE SOCKETS**

I did a test to make sure nothing is wrong with the network or with the server...

I created a simple PING with native sockets....   The App worked just fine without node-redis

```
const net = require('net');
let CONT = 0;

const client = net.createConnection({
        host: ___.REDIS.HOST,
        port: ___.REDIS.PORT,

}, () => {
        client.write('SELECT 11\r\n');
        setInterval( ()=>{
                let ts =  (new Date()).getTime()
                CONT ++;
                client.write(`ECHO ${ts}\r\n`);
        }, 30000);
});
client.on('data', (data) => {
        let payload = data.toString();
        let arr = payload.split('\r\n');
        let ts = parseInt(arr[1]);
        console.log( `${CONT}) PONG ${ (new Date().getTime()) - ts }`);
});
client.on('error', (error) => {
        console.error('error');
        console.error(error);
});
client.on('end', () => {
        console.log('disconnected from server');
});
```

Unfortunately I can't replicate the error in my dev machine. So maybe something is really happening on my production environment.  But  I think that whatever the error is I should be able to handle it. This error keeps killing my app.

thanks...

**Comment by valdorvaldor** [comment]
I did a test to make sure nothing is wrong with the network or with the server...

I created a simple PING with native sockets....   The App worked just fine. So I think something really is happening within node-redis client.

```
const net = require('net');
let CONT = 0;

const client = net.createConnection({
        host: ___.REDIS.HOST,
        port: ___.REDIS.PORT,

}, () => {
        client.write('SELECT 11\r\n');
        setInterval( ()=>{
                let ts =  (new Date()).getTime()
                CONT ++;
                client.write(`ECHO ${ts}\r\n`);
        }, 31000);
});
client.on('data', (data) => {
        let payload = data.toString();
        let arr = payload.split('\r\n');
        let ts = parseInt(arr[1]);
        console.log( `${CONT}) PONG ${ (new Date().getTime()) - ts }`);
});
client.on('error', (error) => {
        console.error('error');
        console.error(error);
});
client.on('end', () => {
        console.log('disconnected from server');
});
```

**Comment by valdorvaldor** [comment]
I FOUND THE ERROR.... (maybe not related with node-redis, but you guys should know)

somewhere in my code I have something like this:

```
const { MongoClient, ReadPreference } = require('mongodb');
let url = `mongodb://${___.MONGO.HOST}:${___.MONGO.PORT}`;
let options = {
        poolSize: ___.MONGO.POOL_SIZE,
        useUnifiedTopology: true,
        authSource: ___.MONGO.DB_NAME,
};
MongoClient.connect( url , options, ( error, client ) => {
        if( error ) console.log( error );
        else console.log( 'MONGO OK');
});
```

As soon as I removed those lines.... the PING worked ok.  I could not believe it. I tested it multiple times.

**Comment by valdorvaldor** [comment]
I found deep inside a duplicate( )  without a error handler.  My bad
