### ISSUE TITLE
NR_CLOSED error intermediately on AUTH recently since last month or so on our Lambda NodeJS 12.x

### ISSUE THREAD

**Issue by ayushnenawati** [NodeRedis/node-redis#1611]
### Issue

> We are using redis node module for Redis client to communicate with Redis server. **We are facing NR_CLOSED error intermediately on AUTH recently since last month or so on our Lambda**. We are using [node redis](https://www.npmjs.com/package/redis) library and redis-labs as our redis server, details of which are mentioned below. 

```
2021-05-25T08:47:00.034Z	ed14111b-3ce2-4354-b46e-3101c27b6efa	ERROR	Uncaught Exception 	
{
    "errorType": "AbortError",
    "errorMessage": "Stream connection ended and command aborted. It might have been processed.",
    "code": "NR_CLOSED",
    "command": "AUTH",
    "args": [
        "*******"
    ],
    "origin": {
        "errorType": "Error",
        "errorMessage": "Redis Error",
        "stack": [
            "Error: Redis Error",
            "    at Object.retry_strategy (/var/task/services/CacheService.js:15:20)",
            "    at RedisClient.connection_gone (/var/task/node_modules/redis/index.js:618:41)",
            "    at RedisClient.on_error (/var/task/node_modules/redis/index.js:410:10)",
            "    at Socket.<anonymous> (/var/task/node_modules/redis/index.js:279:14)",
            "    at Socket.emit (events.js:314:20)",
            "    at Socket.EventEmitter.emit (domain.js:483:12)",
            "    at emitErrorNT (internal/streams/destroy.js:92:8)",
            "    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
            "    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
        ]
    },
    "stack": [
        "AbortError: Stream connection ended and command aborted. It might have been processed.",
        "    at RedisClient.flush_and_error (/var/task/node_modules/redis/index.js:362:23)",
        "    at RedisClient.connection_gone (/var/task/node_modules/redis/index.js:624:18)",
        "    at RedisClient.on_error (/var/task/node_modules/redis/index.js:410:10)",
        "    at Socket.<anonymous> (/var/task/node_modules/redis/index.js:279:14)",
        "    at Socket.emit (events.js:314:20)",
        "    at Socket.EventEmitter.emit (domain.js:483:12)",
        "    at emitErrorNT (internal/streams/destroy.js:92:8)",
        "    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
        "    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
    ]
}
```
Before 2 months we never got this redis error. This is how we have been using it in our code in Lambda. 

**CacheService.js**
```
var redis = require("redis");
var await = require('asyncawait/await');
var async = require('asyncawait/async');
const { promisify } = require('util');

module.exports = function (config) {
	this.client = redis.createClient({
	host: config['redis']['host'],
	port: config['redis']['port'],
	password:config['redis']['password'],
    retry_strategy: function (options) {

        if (options.error) {
            console.log("RedisError: ", options.error);
            return new Error('Redis Error');  //line 15 for error stack reference
        	}
        return 100;
    	}
        });
	
        this.getCachedData = async function getCachedData(key) {
		const getAsync = promisify(this.client.get).bind(this.client);
		var data =  await getAsync(key);
		return data
	}
	
	this.closeConnection = function closeConnection() {
		// close the redis connection
		this.client.quit();
	}
}
```

This is how this service is consumed

```
module.exports = {
    resetConfig: async function (paramConfigData, falconConfigData) {
        if (paramConfigData !== "" && paramConfigData.fetched_at < Date.now()) {
            paramConfigData = ""
        }

        if (paramConfigData === "") {
           

>         try {
>                 var configCacheHandler = new CacheService(falconConfigData)
>                 var cachedConfig = await(configCacheHandler.getCachedData(this.client+":config"));
                 paramConfigData = JSON.parse(cachedConfig);
                 paramConfigData.fetched_at = Date.now() + 10000;
                configCacheHandler.closeConnection();

            } catch (e) {
                console.log("Cached config RedisError:", e)
            }
        }
        return paramConfigData;
    }

}
```
---

### Environment

 - **Node.js Version**: `12.x`
 

 - **Redis Library Version**: `2.8.0`

 - **Redis Version**: `6.0.6`
 

 - **Platform**: `Node JS(Lambda)`

**Comment by leibale** [comment]
do you have a listener on the error event?
```javascript
client.on('error', (err) => console.error(err));
```

in case there is an error event, and there is no listener, node.js will kill the process.
in case there is a listener attached, the listener will get executed, and the the retry strategy will kick in.

**Comment by ayushnenawati** [comment]
@leibale I'm kind of new to this. We are not using this. Can you point out how I can use it in my code shared above?

**Comment by leibale** [comment]
@ayushnenawati in `CacheService.js#modules.exports`
```javascript
this.client = redis.createClient({
  // ...
});

this.client.on('error', err => console.error('Redis Client Error', err));
```
