### ISSUE TITLE
ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by WickedWizard3588** [NodeRedis/node-redis#1633]
Hello there,
I have this infuriating little issue with my Redis Class. It's in Typescript and I'm getting the error `ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value` Although my Key, subKey and the value are strings.

```
import redis, { RedisClient } from 'redis';

export default class Redis {
	public redis: RedisClient;

	public constructor() {
		this.redis = redis.createClient({
			password: 'YOUR_PASS',
		});

		this.redis.on('ready', () => console.log('Redis Ready'));
	}

	public set(guildID: string, paramObj: paramObj): Promise<number | undefined> {
		return new Promise((resolve) => {
			const { key, subKey, value } = paramObj;

			this.redis.hget(key, subKey, (error: Error | null, val: string) => {
				console.log('VAL', JSON.stringify(val));
				if (!JSON.stringify(val)) {
					const obj: { [key: string]: string } = {};
					obj[guildID] = booleanString(value);
					console.log('Appear Here', obj, JSON.stringify(obj), typeof JSON.stringify(obj), typeof obj);
					return this.redis.hset(key, subKey, JSON.stringify(obj), (err: Error | null, reply: number) => {
						console.log('Error', err); // This line logs the error.
						if (err) return resolve(undefined);
						return resolve(reply);
					});
				}

				console.log('Appear Here too');
				const obj = JSON.parse(val);
				obj[guildID] = booleanString(value);
				return this.redis.hset(key, subKey, JSON.stringify(obj), (err: Error | null, reply: number) => {
					console.log('Error', err);
					if (err) return resolve(undefined);
					return resolve(reply);
				});
			});
		});
	}
}

const booleanString = (data: boolean) => (data ? 'Yes' : 'No');
interface paramObj {
	key: 'CommandStatus';
	subKey: string;
	value: boolean;
}
export type returnTypes<K, T, G> = K extends 'CommandStatus'
	? T extends string
		? G extends string
			? boolean
			: { [key: string]: boolean }
		: undefined
	: T extends undefined
	? G extends string
		? string
		: { [key: string]: string }
	: undefined;

void new Redis().set('774645677035880491', { key: 'CommandStatus', subKey: 'help', value: true }).then(console.log);
```
Full Stack below.
```
ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
    at parseError (/media/ubuntu/usbdata/Files/Coding/Javascript/Private/Xyborg/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/media/ubuntu/usbdata/Files/Coding/Javascript/Private/Xyborg/node_modules/redis-parser/lib/parser.js:302:14) {
  command: 'HSET',
  args: [ 'CommandStatus', 'help', '{"774645677035880491":"Yes"}' ], // Here also the array is a string
  code: 'WRONGTYPE'
}
```
You can see that I log the `types` using the `typeof` operator. 

### Environment
Node Version: 14.17.3 (LTS)
Redis Version: 6.2.4
Platform: Ubuntu 20.04 LTS

Thank you

**Comment by leibale** [comment]
This error is from the `redis-server` itself, and it means that the type of the value stored at `key` is not a `hashmap`. You can use the [`TYPE`](https://redis.io/commands/type) command to check what is the type of the value stored at a certain key.
