### ISSUE TITLE
`Error: Cannot send commands in PubSub mode` after unsubscribing

### ISSUE THREAD

**Issue by GCSBOSS** [NodeRedis/node-redis#1652]
### Issue

Given the following test scenario.

```js
(async function(){
    const redis = require('redis').createClient();
    await redis.connect();
    await redis.subscribe('abc', Function.prototype);
    await redis.unsubscribe();
    await redis.quit();
})();
```

I get this error: 

```
Error: Cannot send commands in PubSub mode
      at RedisCommandsQueue.addEncodedCommand (node_modules\redis\dist\lib\commands-queue.js:82:35)
      at C:\Users\Guilherme\Projetos\nodecaf\redis\node_modules\redis\dist\lib\client.js:168:83
      at RedisSocket.quit (node_modules\redis\dist\lib\socket.js:80:19)
      at RedisClient.QUIT (node_modules\redis\dist\lib\client.js:167:71)
      at Context.<anonymous> (test\spec.js:15:21)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Apparently, the client is only leaving the PubSub mode **some time after** the Promise returned from `redis.unsubscribe()` resolves.

Is this a bug, or should I rely on some event to know when I'm out of Pub/Sub mode?

---

### Environment

 - **Node.js Version**: `v14.5.0`
 - **Redis Server Version**: `Redis server v=6.0.9 malloc=jemalloc-5.1.0 bits=64 build=12c354e6793cb936`
 - **Platform**: `Windows 10`
 - **NodeRedis Version**: `4.0.0-rc.1`

**Comment by chenqq2436** [comment]
The problem is now closed, but how can we write without reporting an error ?

**Comment by marco-meini** [comment]
I still have this error with version 4.3.1

I used promises how described in the migration guide but I have to set legacyMode=true to avoid the error.

this is the stack:

(node:54620) UnhandledPromiseRejectionWarning: Error: Cannot send commands in PubSub mode
    at RedisCommandsQueue.addCommand (/developer/__github__/YouNeed/yn-ws/node_modules/@redis/client/dist/lib/client/commands-queue.js:72:35)
    at RedisSocket.socketInitiator (/developer/__github__/YouNeed/yn-ws/node_modules/@redis/client/dist/lib/client/index.js:333:81)
    at RedisSocket._RedisSocket_connect (/developer/__github__/YouNeed/yn-ws/node_modules/@redis/client/dist/lib/client/socket.js:138:77)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Commander.connect (/developer/__github__/YouNeed/yn-ws/node_modules/@redis/client/dist/lib/client/index.js:166:9)
