### ISSUE TITLE
HMSET Command is not exists in redis@next

### ISSUE THREAD

**Issue by yehiaelsayed** [NodeRedis/node-redis#1666]
### Issue

> HMSET command does not exist in the client object after upgrade to redis@next  

```
HMSET user:1001 name "Mary Jones" password "hidden" email "mjones@example.com 
```

**Comment by leibale** [comment]
"As per Redis 4.0.0, HMSET is considered deprecated. Please prefer HSET in new code."

We're still considering if deprecated commands should be implemented or not.

**Comment by meftunca** [comment]
HSET not working 

```bash
Error: The client is closed
    at RedisClient._RedisClient_sendCommand (/Users/devloops/Desktop/my_projects/learn_redis/node_modules/redis/dist/lib/client.js:383:15)
    at RedisClient.commandsExecutor (/Users/devloops/Desktop/my_projects/learn_redis/node_modules/redis/dist/lib/client.js:174:129)
    at RedisClient.BaseClass.<computed> [as hSet] (/Users/devloops/Desktop/my_projects/learn_redis/node_modules/redis/dist/lib/commander.js:12:29)
    at Object.<anonymous> (/Users/devloops/Desktop/my_projects/learn_redis/index.ts:6:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/devloops/Desktop/my_projects/learn_redis/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/ql/7bst8c414czb3401xnx17x_c0000gn/T/ts-node-dev-hook-2834112917993419.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/ql/7bst8c414czb3401xnx17x_c0000gn/T/ts-node-dev-hook-2834112917993419.js:114:20)
    at require.extensions.<computed> (/private/var/folders/ql/7bst8c414czb3401xnx17x_c0000gn/T/ts-node-dev-hook-2834112917993419.js:71:20)
[ERROR] 05:52:20 Error: The client is closed
```

**Comment by leibale** [comment]
Make sure you use `await client.connect()` before you try to execute a command

**Comment by meftunca** [comment]
so how can i extends to classes

**Comment by meftunca** [comment]
Like That...

```js
class Controller extends RedisClient{

constructor(config){
super(config)
}

}
```

**Comment by leibale** [comment]
What do you mean? How to store objects?
```javascript
client.HSET('key', { field1: '1', field2: '2' });
```
Note that hash store everything as a string

**Comment by leibale** [comment]
Why do you need to extend the client class? What are you trying to achieve?

**Comment by meftunca** [comment]
To write more organized and less code.

**Comment by NovaAtWarren** [comment]
> To write more organized and less code.

Surely, instead of extending a class that may change with an update, it would be better to make an object that contains an instance of that class.
For instance:

```typescript
class Controller{
    public client: RedisClient;

    constructor(config){
        client = redis.createClient(config);
        // ...
    }
}
```

That way, when something changes in `node-redis`, you change how your class handles it, not your entire codebase.
